M48
; DRILL file {KiCad (6.0.0)} date Wed Nov  9 00:35:20 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-11-09T00:35:20-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X109.855Y-58.42
X109.855Y-100.33
X168.275Y-58.42
X168.275Y-100.33
T0
M30
